export enum SOCKET_EVENTS {
  CONNECT = "connect",
  DISCONNECT = "disconnect",
  ERROR = "error",
  NOTIFICATION = "notification",
  JOINED_ROOM = "joined_room",
  LEFT_ROOM = "left_room",
  JOIN_ROOM = "join_room",
  LEAVE_ROOM = "leave_room",
  PLAYER_JOINED = "player_joined",
  PLAYER_LEFT = "player_left",
  HEARTBEAT = "heartbeat",
  ADD_BUG = "add_bug",
  BUG_ADDED = "bug_added",
  KILL_BUG = "kill_bug",
  BUG_KILLED = "bug_killed",
  UPDATE_BUG_HEALTH = "update_bug_health",
  BUG_HEALTH_UPDATED = "bug_health_updated",
  PLAYER_MOVE = "player_move",
  PLAYER_MOVED = "player_moved",
  FIRE_BULLET = "fire_bullet",
  BULLET_FIRED = "bullet_fired",
  UPDATE_BULLETS = "update_bullets",
  BULLETS_UPDATED = "bullets_updated",
  GAME_OVER = "game_over",
  RESTART_GAME = "game_restart",
  GAME_RESTARTED = "game_restarted",
}
